export const styleConfigs = {
  basic: {
    title: "Choose your style",
    types: {
      shirt: {
        label: "Shirt",
        description: "Classic collar, plain hem & adjustable cuffs.",
        layers: [
          "/assets/shirt/body-bluestripe.png",
          "/assets/shirt/hands-bluestripe.png",
          "/assets/shirt/collar-bluestripe.png",
          "/assets/shirt/cuff-bluestripe.png",
          "/assets/shirt/button-bluestripe.png",
        ],
        redirect: "/customize/shirt",
      },
      tuxedo: {
        label: "Tuxedo",
        description: "Peak lapel, silk finish & formal structure.",
        layers: [
          "/assets/tuxedo/body.png",
          "/assets/tuxedo/hand.png",
          "/assets/tuxedo/pocketlow.png",
          "/assets/tuxedo/pocketup.png",
          "/assets/tuxedo/callar.png",
          "/assets/tuxedo/callar1.png",
          "/assets/tuxedo/corcallar.png",
          "/assets/tuxedo/tiy.png",
          "/assets/tuxedo/button.png",
        ],
        redirect: "/customize/tuxedo",
      },
      pant: {
        label: "Pant",
        description: "Tailored fit, comfortable waist & premium fabric.",
        layers: [
          "/assets/shirt/body-bluestripe.png",
          "/assets/shirt/hands-bluestripe.png",
          "/assets/shirt/collar-bluestripe.png",
          "/assets/shirt/cuff-bluestripe.png",
          "/assets/shirt/button-bluestripe.png",
        ],
        redirect: "/customize/pant",
      },
      "tuxedo-pant": {
        label: "Tuxedo Pant",
        description: "Formal evening wear with satin stripe.",
        layers: [
          "/assets/tuxedo/body.png",
          "/assets/tuxedo/hand.png",
          "/assets/tuxedo/pocketlow.png",
          "/assets/tuxedo/pocketup.png",
          "/assets/tuxedo/callar.png",
          "/assets/tuxedo/callar1.png",
          "/assets/tuxedo/corcallar.png",
          "/assets/tuxedo/tiy.png",
          "/assets/tuxedo/button.png",
        ],
        redirect: "/customize/tuxedo-pant",
      },
      jacket: {
        label: "Jacket",
        description: "Classic blazer with modern tailoring.",
        layers: [
          "/assets/shirt/body-bluestripe.png",
          "/assets/shirt/hands-bluestripe.png",
          "/assets/shirt/collar-bluestripe.png",
          "/assets/shirt/cuff-bluestripe.png",
          "/assets/shirt/button-bluestripe.png",
        ],
        redirect: "/customize/jacket",
      },
      "tuxedo-jacket": {
        label: "Tuxedo Jacket",
        description: "Elegant dinner jacket with satin lapels.",
        layers: [
          "/assets/tuxedo/body.png",
          "/assets/tuxedo/hand.png",
          "/assets/tuxedo/pocketlow.png",
          "/assets/tuxedo/pocketup.png",
          "/assets/tuxedo/callar.png",
          "/assets/tuxedo/callar1.png",
          "/assets/tuxedo/corcallar.png",
          "/assets/tuxedo/tiy.png",
          "/assets/tuxedo/button.png",
        ],
        redirect: "/customize/tuxedo-jacket",
      },
      waistcoat: {
        label: "Waistcoat",
        description: "Sophisticated vest for formal occasions.",
        layers: [
          "/assets/shirt/body-bluestripe.png",
          "/assets/shirt/hands-bluestripe.png",
          "/assets/shirt/collar-bluestripe.png",
          "/assets/shirt/cuff-bluestripe.png",
          "/assets/shirt/button-bluestripe.png",
        ],
        redirect: "/customize/waistcoat",
      },
      coat: {
        label: "Coat",
        description: "Elegant outerwear for all seasons.",
        layers: [
          "/assets/shirt/body-bluestripe.png",
          "/assets/shirt/hands-bluestripe.png",
          "/assets/shirt/collar-bluestripe.png",
          "/assets/shirt/cuff-bluestripe.png",
          "/assets/shirt/button-bluestripe.png",
        ],
        redirect: "/customize/coat",
      },
    },
  },

  premium: {
    title: "Choose premium fabric",
    types: {
      shirt: {
        label: "Premium Shirt",
        description: "Luxury cotton premium fabric.",
        layers: [
          "/assets/shirt/body-bluestripe.png",
          "/assets/shirt/collar-bluestripe.png",
          "/assets/shirt/cuff-bluestripe.png",
          "/assets/shirt/hands-bluestripe.png",
          "/assets/shirt/button-bluestripe.png",
        ],
        redirect: "/customize/premium-shirt",
      },
      tuxedo: {
        label: "Premium Tuxedo",
        description: "Silk premium tuxedo.",
        layers: [
          "/assets/premium/tux.png",
        ],
        redirect: "/customize/premium-tuxedo",
      },
      pant: {
        label: "Premium Pant",
        description: "Luxury wool formal pant.",
        layers: [
          "/assets/shirt/body-bluestripe.png",
          "/assets/shirt/hands-bluestripe.png",
          "/assets/shirt/collar-bluestripe.png",
          "/assets/shirt/cuff-bluestripe.png",
          "/assets/shirt/button-bluestripe.png",
        ],
        redirect: "/customize/pant",
      },
      "tuxedo-pant": {
        label: "Premium Tuxedo Pant",
        description: "Silk stripe formal evening pant.",
        layers: [
          "/assets/tuxedo/body.png",
          "/assets/tuxedo/hand.png",
          "/assets/tuxedo/pocketlow.png",
          "/assets/tuxedo/pocketup.png",
          "/assets/tuxedo/callar.png",
          "/assets/tuxedo/callar1.png",
          "/assets/tuxedo/corcallar.png",
          "/assets/tuxedo/tiy.png",
          "/assets/tuxedo/button.png",
        ],
        redirect: "/customize/tuxedo-pant",
      },
      jacket: {
        label: "Premium Jacket",
        description: "Italian wool tailored jacket.",
        layers: [
          "/assets/shirt/body-bluestripe.png",
          "/assets/shirt/hands-bluestripe.png",
          "/assets/shirt/collar-bluestripe.png",
          "/assets/shirt/cuff-bluestripe.png",
          "/assets/shirt/button-bluestripe.png",
        ],
        redirect: "/customize/jacket",
      },
      "tuxedo-jacket": {
        label: "Premium Tuxedo Jacket",
        description: "Silk lapel evening jacket.",
        layers: [
          "/assets/tuxedo/body.png",
          "/assets/tuxedo/hand.png",
          "/assets/tuxedo/pocketlow.png",
          "/assets/tuxedo/pocketup.png",
          "/assets/tuxedo/callar.png",
          "/assets/tuxedo/callar1.png",
          "/assets/tuxedo/corcallar.png",
          "/assets/tuxedo/tiy.png",
          "/assets/tuxedo/button.png",
        ],
        redirect: "/customize/tuxedo-jacket",
      },
      waistcoat: {
        label: "Premium Waistcoat",
        description: "Silk back formal vest.",
        layers: [
          "/assets/shirt/body-bluestripe.png",
          "/assets/shirt/hands-bluestripe.png",
          "/assets/shirt/collar-bluestripe.png",
          "/assets/shirt/cuff-bluestripe.png",
          "/assets/shirt/button-bluestripe.png",
        ],
        redirect: "/customize/waistcoat",
      },
      coat: {
        label: "Premium Coat",
        description: "Cashmere wool overcoat.",
        layers: [
          "/assets/shirt/body-bluestripe.png",
          "/assets/shirt/hands-bluestripe.png",
          "/assets/shirt/collar-bluestripe.png",
          "/assets/shirt/cuff-bluestripe.png",
          "/assets/shirt/button-bluestripe.png",
        ],
        redirect: "/customize/coat",
      },
    },
  },
};